### ISSUE TITLE
Training Hangs during failure handling on a large cluster

### ISSUE THREAD

**Issue by amogkam** [ray-project/xgboost_ray#15] opened 2020-11-24 18:20 UTC
I am running simple.py with 700 actors, each with 1 CPU on a 200 node cluster. `max_actor_restarts` is set to 1.

I start running the script and **after** training begins, I start to kill raylets via `ray kill-random-node`. I make sure this happens only after I see `[RayXGBoost] Starting XGBoost training.` being printed out, so at this point all actors have been created and the data is all loaded.

I first see this warning message which is good:
```
2020-11-23 11:34:40,000	WARNING main.py:480 -- A Ray actor died during training. Trying to restart and continue training from last checkpoint.
```

So now I would expect training to start from the last checkpoint. But now a bunch of these warning messages constantly get printed out:
```
(pid=raylet, ip=172.31.22.238) AssertError:check ack & check pt  cannot occur together with normal ops, shutting down process
(pid=raylet, ip=172.31.22.238) AssertError:check ack & check pt  cannot occur together with normal ops, shutting down process
(pid=raylet, ip=172.31.22.238) AssertError:check ack & check pt  cannot occur together with normal ops, shutting down process
(pid=raylet, ip=172.31.16.115) AssertError:check ack & check pt  cannot occur together with normal ops, shutting down process
```

And training now seems to hang. Here is the stack on the main thread for the driver process. It’s hanging on a `queue.empty` call.
```
Thread 107336 (idle): "MainThread"
    get_objects (ray/worker.py:316)
    get (ray/worker.py:1392)
    empty (ray/util/queue.py:37)
    _train (xgboost_ray/main.py:353)
    train (xgboost_ray/main.py:475)
    main (simple.py:37)
    <module> (simple.py:47)
```

**Comment by krfricke** [comment] 2020-11-24 18:59
I've seen this, too. I did some debug printing and it seems that the actors are registered at the Rabit tracker (i.e. they send a "start" message to the tracker) but don't start with the actual training - no messages are received at the tracker afterwards.

**Comment by amogkam** [comment] 2020-12-01 18:49
Tried this again and am now seeing this being printed a bunch of times 
```
E1201 10:49:02.755669192   31670 error.cc:276]               Error 0x7f19ed9559e0 is full, dropping error 0x7f0f6cd88d00 = {"created":"@1606848542.755643406","description":"Broken pipe","errno":32,"fd":1431,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":986,"grpc_status":14,"os_error":"Broken pipe","syscall":"sendmsg","target_address":"ipv4:172.31.30.175:57312"}
E1201 10:49:02.755766211   31670 error.cc:276]               Error 0x7f19ed9559e0 is full, dropping error 0x7f12de5988d0 = {"created":"@1606848542.755732181","description":"Broken pipe","errno":32,"fd":1431,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":986,"grpc_status":14,"os_error":"Broken pipe","syscall":"sendmsg","target_address":"ipv4:172.31.30.175:57312"}
E1201 10:49:02.755879947   31670 error.cc:276]               Error 0x7f19ed9559e0 is full, dropping error 0x7f0f6cd8b3c0 = {"created":"@1606848542.755848053","description":"Broken pipe","errno":32,"fd":1431,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":986,"grpc_status":14,"os_error":"Broken pipe","syscall":"sendmsg","target_address":"ipv4:172.31.30.175:57312"}
E1201 10:49:02.755960824   31670 error.cc:276]               Error 0x7f19ed9559e0 is full, dropping error 0x7f12de598ac0 = {"created":"@1606848542.755937905","description":"Broken pipe","errno":32,"fd":1431,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":986,"grpc_status":14,"os_error":"Broken pipe","syscall":"sendmsg","target_address":"ipv4:172.31.30.175:57312"}
E1201 10:49:02.756050129   31670 error.cc:276]               Error 0x7f19ed9559e0 is full, dropping error 0x7f12dec80d40 = {"created":"@1606848542.756027006","description":"Broken pipe","errno":32,"fd":1431,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":986,"grpc_status":14,"os_error":"Broken pipe","syscall":"sendmsg","target_address":"ipv4:172.31.30.175:57312"}
E1201 10:49:02.756153945   31670 error.cc:276]               Error 0x7f19ed9559e0 is full, dropping error 0x7f12dec80b50 = {"created":"@1606848542.756124334","description":"Broken pipe","errno":32,"fd":1431,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":986,"grpc_status":14,"os_error":"Broken pipe","syscall":"sendmsg","target_address":"ipv4:172.31.30.175:57312"}
E1201 10:49:02.756250363   31670 error.cc:276]               Error 0x7f19ed9559e0 is full, dropping error 0x7f0f6cbaf230 = {"created":"@1606848542.756222554","description":"Broken pipe","errno":32,"fd":1431,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":986,"grpc_status":14,"os_error":"Broken pipe","syscall":"sendmsg","target_address":"ipv4:172.31.30.175:57312"}
E1201 10:49:02.756344354   31670 error.cc:276]               Error 0x7f19ed9559e0 is full, dropping error 0x7f12defe89f0 = {"created":"@1606848542.756321583","description":"Broken pipe","errno":32,"fd":1431,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":986,"grpc_status":14,"os_error":"Broken pipe","syscall":"sendmsg","target_address":"ipv4:172.31.30.175:57312"}
E1201 10:49:02.756446744   31670 error.cc:276]               Error 0x7f19ed9559e0 is full, dropping error 0x7f12defea5c0 = {"created":"@1606848542.756421613","description":"Broken pipe","errno":32,"fd":1431,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":986,"grpc_status":14,"os_error":"Broken pipe","syscall":"sendmsg","target_address":"ipv4:172.31.30.175:57312"}
E1201 10:49:02.756475018   31670 error.cc:276]               Error 0x7f19ed9559e0 is full, dropping error 0x7f0f6cbb0590 = {"created":"@1606848542.756456132","description":"Broken pipe","errno":32,"fd":1431,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/tcp_posix.cc","file_line":986,"grpc_status":14,"os_error":"Broken pipe","syscall":"sendmsg","target_address":"ipv4:172.31.30.175:57312"}
```

**Comment by krfricke** [comment] 2021-04-08 14:50
Cannot reproduce on latest master, closing for now.

**Closed by krfricke** 2021-04-08 14:50 UTC
